### ISSUE TITLE
arm-anykav200-linux-uclibcgnueabi-gcc download

### ISSUE THREAD

**Issue by ricardojlrufino** [TuyaInc/TUYA_IPC_SDK#3]
Where i can find arm-anykav200-linux-uclibcgnueabi-gcc ??

**Comment by jimopt** [comment]
check https://github.com/tuya/tuya-iotos-embeded-sdk-multimedia/blob/master/Linux/download.md













At 2022-02-14 02:56:12, "Ricardo JL Rufino" ***@***.***> wrote:

Where i can find arm-anykav200-linux-uclibcgnueabi-gcc ??

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ricardojlrufino** [comment]
Thank you !!!!
